networks:
  robotics-network:
    driver: bridge


services:
  robotics:
    image: thiagolages/template-robotics:latest
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        COPPELIA_VERSION: "4_10_0"
        COPPELIA_REVISION: "rev0"
        COPPELIA_OS: "Ubuntu22_04"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw   # GUI sharing
      - ./src:/home/thiago/workspace/src
      - ./data:/home/thiago/workspace/data
      - ./scripts:/home/thiago/workspace/scripts
    command: /home/thiago/workspace/scripts/command.sh
    environment:
      DISPLAY:
      QT_X11_NO_MITSHM: 1
      PYTHONUNBUFFERED: 1
      TERM: xterm-256color
      COPPELIA_ZMQ_PORT: 23000
    hostname: robotics
    container_name: robotics
    network_mode: host
    ipc: host
    tty: true
    stdin_open: true
