name: Reusable Python Build
on:
  workflow_call:
    inputs:
      python-version:
        type: string
        default: "3.11"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache: pip
      - run: pip install -r requirements.txt
      - run: python -c "print('hello from reusable build')"
